### ISSUE TITLE
Problem with `lsm_l_ai()`

### ISSUE THREAD

**Issue by Nowosad** [r-spatialecology/landscapemetrics#82] opened 2019-02-24 10:58 UTC
Today, I unexpectedly came across a problem with `lsm_l_ai()` - it gave `NA` on some of my small raster. 
My raster file - [test.zip](https://github.com/r-spatialecology/landscapemetrics/files/2897819/test.zip).

```r
library(raster)
library(landscapemetrics)

x = raster("test.tif")
lsm_l_ai(x)

#> # A tibble: 1 x 6
#>   layer level     class    id metric value
#>   <int> <chr>     <int> <int> <chr>  <dbl>
#> 1     1 landscape    NA    NA ai        NA

```

**Comment by Nowosad** [comment] 2019-02-24 11:13
https://github.com/r-spatialecology/landscapemetrics/blob/d87ebd2f0acef4146bef7f680adc95bc957e802b/R/lsm_c_ai.R#L163

Shouldn't the aggregation be 100 for only one-cell classes? @mhesselbarth @marcosci

**Comment by Nowosad** [comment] 2019-02-24 11:20
Ok, based on the last quote, it seams that the **landscapemetrics** implementation is correct. However, I am still unsure if this approach is the best.

WIP

**Comment by Nowosad** [comment] 2020-12-31 09:06
Hi @mhesselbarth @bitbacchus, 
this issue bit me again. I am calculating landscape metrics for hundreds of landscapes. Some of them have one-cell categories, and thus I get `NA` for `lsm_l_ai()`. Could one of you try to calculate AI on the landscape level based on the data in the following example using fragstat and let me know if the result is also `NA`?

``` r
library(raster)
#> Loading required package: sp
library(landscapemetrics)
data("landscape")

# original data -----------------------------------------------------------
plot(landscape, col = c("red", "green", "blue"))
```

![](https://i.imgur.com/V2fUlvT.png)

``` r
lsm_l_ai(landscape)
#> # A tibble: 1 x 6
#>   layer level     class    id metric value
#>   <int> <chr>     <int> <int> <chr>  <dbl>
#> 1     1 landscape    NA    NA ai      81.1

# data with a one-cell class ----------------------------------------------
landscape[444] = 4

plot(landscape, col = c("red", "green", "blue", "yellow"))
```

![](https://i.imgur.com/JKWSdVq.png)

``` r
lsm_l_ai(landscape)
#> # A tibble: 1 x 6
#>   layer level     class    id metric value
#>   <int> <chr>     <int> <int> <chr>  <dbl>
#> 1     1 landscape    NA    NA ai        NA
```

<sup>Created on 2020-12-31 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by mhesselbarth** [comment] 2020-12-31 14:50
I don't have a Windows machine available anymore, sorry.

Reading the documentation again, it kind of makes sense that it is NA for only one cell though since there are no adjacencies at all in this case.

**Comment by mhesselbarth** [comment] 2021-01-05 14:54
Oh...but I see the problem now. It actually is a strange behavior if more than 1 class exists as in your example above. I think the problem is that we need to the take the sum of AI on class level, which will be NA if one class (in your example class4) is NA. We could simply add `na.rm = TRUE` to the sum. Would be indeed interesting what FRAGSTATS returns...

**Comment by Nowosad** [comment] 2021-01-06 16:24
@mhesselbarth I just remembered that I have a remote access to some windows computers at my Uni. 

I created a tiny simple raster:

``` r
library(landscapemetrics)
library(raster)
#> Loading required package: sp
r = raster(matrix(c(rep(1, 8), 2, rep(1, 7)), ncol = 4))

lsm_l_ai(r)
#> # A tibble: 1 x 6
#>   layer level     class    id metric value
#>   <int> <chr>     <int> <int> <chr>  <dbl>
#> 1     1 landscape    NA    NA ai        NA
```

It returns `NA` in **landscapemetrics**, however, when I calculated AI in Fragstat, the result was:

![2021-01-06_17-19](https://user-images.githubusercontent.com/3457131/103792352-d4505f00-5043-11eb-971a-c8b5216ca00a.png)

This is consistent with your idea above:

``` r
library(landscapemetrics)
library(raster)
#> Loading required package: sp
r <- raster(matrix(c(rep(1, 8), 2, rep(1, 7)), ncol = 4))

# get aggregation index for each class
ai <- lsm_c_ai(r)

# get proportional class area
pland <- lsm_c_pland(r, directions = 8)

# final AI index
(sum(ai$value * (pland$value / 100), na.rm = TRUE))
#> [1] 89.48864
```

<sup>Created on 2021-01-06 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by mhesselbarth** [comment] 2021-01-06 16:49
Okay, so that's an easy fix. I can do that later today. 

Can you please create a raster with three classes (2 classes with more than one cell and 1 class with only one cell) and calculate AI on class level as well just to make sure the results will be numeric for two classes and NA for one class

**Comment by Nowosad** [comment] 2021-01-06 17:03
``` r
library(raster)
#> Loading required package: sp
r2 = raster(matrix(c(1, 1, 1, 3, 3, 3, 3, 3, 2, 1, 1, 3, 3, 1, 1, 1), ncol = 4))
plot(r2)
```

![](https://i.imgur.com/DKL8A8o.png)

Fragstats results:

<sup>Created on 2021-01-06 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
![2021-01-06_18-01_1](https://user-images.githubusercontent.com/3457131/103798000-71fa5d00-5049-11eb-8719-89ca80e7f8de.png)
![2021-01-06_18-01](https://user-images.githubusercontent.com/3457131/103798008-745cb700-5049-11eb-86d4-8306524c9267.png)

**Comment by mhesselbarth** [comment] 2021-01-06 17:59
017202bfe18923f26a4fcfed0288d2b91d8beb7c
Perfect. Should be fixed!

**Closed** 2021-01-06 18:49 UTC
Labels: bug

**Comment by Nowosad** [comment] 2021-01-06 20:46
Awesome. Thanks Max!
