### ISSUE TITLE
Moving window feature of FRAGSTATS

### ISSUE THREAD

**Issue by gregforcey** [r-spatialecology/landscapemetrics#80] opened 2019-02-12 21:05 UTC
This isn't really an issue with `landscapemetrics` per se but more of a usage question. Is there any way to replicate the moving window feature in `FRAGSTATS` where you can output a raster that characterizes a particular metric for a given land use type (e.g., a grid could characterize percent forest)? I know the `raster` package has the `focal` function which seems to at least partially do this. But the function used with `focal` has to output a single number which functions in the `landscapemetrics` package do not do.

So if I want to use the moving window analysis feature and output grids describing the landscape am I stuck to using `FRAGSTATS`?

**Comment by mhesselbarth** [comment] 2019-02-13 08:19
Currently, that is not possible, but I think something to think about for the future @marcosci @Nowosad ? Shouldn't be too hard using raster's `foca()l` function, right?

**Comment by Nowosad** [comment] 2019-02-16 13:24
Yep, I think it could be a nice feature. I am not very familiar with the moving window options in FRAGSTATS, so please correct me if I am wrong:

1. **Input** - (a) landscape, (b) moving window size, (c) some of the arguments in `calculate_lsm()` (https://github.com/r-spatialecology/landscapemetrics/blob/master/R/calculate_lsm.R), (d) if a class level is chosen - then a value of selected class
2. **Internals** - calculation of the selected metric in a window, move the window, calculation of the selected metric in a window, repeat...
3. **Output** - raster with a resolution of the moving window size (?)

**Comment by marcosci** [comment] 2019-02-17 21:26
The output would then be a rasterstack that has the same dimensions as the tibble, or?
So for every row from `calculate_lsm` we would have a single raster in a rasterstack, or?

I like the idea and I think we looked at the remaining functionality of FRAGSTATS some weeks ago ... but I have the feeling that the focal function from the raster package could be way to slow for the biggish rasters people seem to use here :-) @laurajanegraham will maybe second that opinion.

**Comment by mhesselbarth** [comment] 2019-02-18 06:17
I thought the output would be just one raster (same dimensions as the input) where every focal cell gets the value of the moving window, e.g. the percentage of a certain land-cover class.

From the FRAGSTATS manual (https://www.umass.edu/landeco/research/fragstats/documents/fragstats.help.4.2.pdf):
> [... ] Within each window, each selected metric at the class or landscape level is computed and the value returned to the focal (center) cell. [...]

**Comment by laurajanegraham** [comment] 2019-02-18 12:53
The raster focal function is actually reasonable if the function being calculated is mean or sum. So for proportion or diversity metrics it would be okay. It's when you need to start using other (or user-defined) functions that the timing increases. The reason for this is that they have coded the mean/sum versions in C++, but any other functions get diverted into a slower version of focal. 

I have some diversity metrics calculated in grainchanger (https://github.com/laurajanegraham/grainchanger) using only the mean/sum function within focal. They are still fairly slow with large window sizes (or datasets), but I think this may just be an issue with moving window analysis rather than the focal function.

**Comment by marcosci** [comment] 2019-02-18 18:48
> I thought the output would be just one raster (same dimensions as the input) where every focal cell gets the value of the moving window, e.g. the percentage of a certain land-cover class.
> 
> From the FRAGSTATS manual (https://www.umass.edu/landeco/research/fragstats/documents/fragstats.help.4.2.pdf):
> 
> > [... ] Within each window, each selected metric at the class or landscape level is computed and the value returned to the focal (center) cell. [...]

If you have 3 classes, how would you put 3 values for enn_mn in a raster cell? I think you need a stack in the end, or?

And Laura that sounds for a good justification to just use focal :-) Would also mean that we just have to plugin calculate_lsm there, or?

**Comment by mhesselbarth** [comment] 2019-02-18 18:51
> If you have 3 classes, how would you put 3 values for enn_mn in a raster cell? I think you need a stack in the end, or?

Yeah right...didn't think about class level. So on class level it would be a stack/list (with as many layers as classes) and on landscape level just one RasterLayer

**Comment by marcosci** [comment] 2019-02-27 03:44
So, something in the line of that?

``` r
calculate_lsm_focal <- function(x, 
                                nrow, 
                                ncol, 
                                metric) {
    
    raster_window <- raster::raster(matrix(x, nrow, ncol))
    
    lsm_value <- landscapemetrics::calculate_lsm(raster_window, what = metric)
    
    lsm_value$value
    
    
}

w <- raster::focalWeight(landscapemetrics::landscape, 2, type = "rectangle")
w <- ifelse(w > 0, 1, NA)

out <-
    raster::focal(landscapemetrics::landscape, w, function(x) {
        calculate_lsm_focal(x, nrow(w), ncol(w), "lsm_l_cai_cv")
    })


landscapetools::show_landscape(out)
```

![](https://i.imgur.com/VNVOI4I.png)

<sup>Created on 2019-02-27 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by mhesselbarth** [comment] 2019-02-28 14:50
Okay... I think `window_lsm()` is what we want (9adf643d).

I didn't check in detail, but the returning values seemed reasonable to me at first glance. 

I modified @marcosci suggestion a little bit to avoid too many conversion between raster and matrix (and vice versa). I did some benchmarking and the speed gain was quite a lot.

The return is always a nested list to be type stable. The first level includes the layers (if a RasterStack is provided). The second level includes the different metrics. Right now, only landscape level metrics are allowed. Maybe we could think about also including class level metrics (and returning a RasterStacks instead of a RasterLayers), but this makes everything more complicated.

**Comment by Nowosad** [comment] 2019-03-02 13:09
@mhesselbarth I've played with the new function for a while and it looks truly awesome. 
I think the further steps could be:
1. Add a support for class level metrics - it would fit nicely as rasterstacks. There could even be an option of selecting just one class...
2. Add tests. 
3. Write a vignette describing how  the moving window works.

What do you think? @mhesselbarth, @marcosci ?

**Comment by mhesselbarth** [comment] 2019-03-02 16:03
All props go to @marcosci, he came up with the basic idea 👍 

1. I think this would be very cool, just makes it a bit more complicated because we probably need to add one loop/apply to go through all classes and stack the results somehow
2. Agreed
3. Agreed

**Comment by mhesselbarth** [comment] 2019-03-04 06:46
I added some first tests. While doing this, I noticed that the window matrix must be at least 3x3 and additionally have uneven sides. `raster` actually returns an error message when using the `focal()` function. Do we want to check that even before and throw our own error message, or is the `raster` one good enough? 

``` 
> window_lsm(landscape, window = matrix(1, nrow = 4, ncol = 4), what = "lsm_l_pr")
 Error in .local(x, ...) : w must have uneven sides 
```

**Comment by mhesselbarth** [comment] 2019-03-05 07:05
The feature is now implemented in the development version on GitHub and will be part of the next CRAN update. 
Currently, only landscape level metrics are supported, however, class level metrics will probably be possible some point in the future.

``` 
devtools::install_github("r-spatialecology/landscapemetrics)

window <- matrix(1, nrow = 5,ncol = 5)
window_lsm(landscape, window = window, what = c("lsm_l_pr", "lsm_l_joinent"))
``` 

I will close this for now, please re-open if you miss something.

**Comment by mhesselbarth** [comment] 2019-04-11 07:55
Ups...I just found a bug in `window_lsm()` for some metrics. Please make sure you install the most recent development version using `devtools::install_github("r-spatialecology/landscapemetrics"). Will also be part of the next CRAN update.

**Comment by ZanetaKaszta** [comment] 2019-11-24 05:24
Hi, I tried to use 'window_lsm`to run patch density and aggregation index on landscape level and I'm getting this error:

Error in seq_len(nrow(area_patch)) : 
  argument must be coercible to non-negative integer
In addition: Warning message:
In seq_len(nrow(area_patch)) : first element used of 'length.out' argument

This is the code I used:
`window_lsm(r2,window=window,what = c("lsm_l_pd", "lsm_l_ai")`

 I tried to run these two metrics also separately and I received same error. 
Example from your package documentation worked for me. Do you think this might be a bug for these two metrics (and few others I tried e.g., edge density) or do I do something wrong?

I would appreciate your feedback

**Comment by Nowosad** [comment] 2019-11-24 07:29
Hi @ZanetaKaszta , I believe the issue is related to #140 - your data has some NA values and this causes the error. We need to think on how to fix it.

**Comment by mhesselbarth** [comment] 2019-11-26 14:14
I fixed the issue in #140 (d35fe9d / 8530508). Not sure how that the raster::focal() function now deals with the NA values. @ZanetaKaszta can you maybe provide your data here so we can check what's going on?

**Comment by ZanetaKaszta** [comment] 2019-11-26 19:46
Hi Jakub and Max, Thank you so much for your fast reply. I think your package is extremely useful. I'm   usually using Fragstats moving window approach and having that integrated with R would be amazing. I'm away at the moment and will definitely send you the data next week.

I don not think there is any NA in my raster but I will confirm that next week. I thought it might have been a NA issue so I tested a subset of my study area without the edge, however it could happen that there are few pixels with NA remaining. Nevertheless, the error appeared quite quickly...

**Comment by JKLockhart** [comment] 2021-03-24 00:25
Hi, I'm trying to calculate the number of forest patches within the focal landscape using a moving window approach. When using the following code, the analysis runs without errors, but never seems to complete itself: 

s <- matrix(1, nrow = 161, ncol = 161)
result <- window_lsm(Forest358, window = s, 
                                      what = c("lsm_l_np"))

I am wondering if it is just taking a very long time to complete the analysis because of the size of my moving window - each cell is a 30x30 m resolution and the overall area of the raster is approximately 50km x 100km.  Or am I missing something from my code? If the former, are there other options for processing large spatial areas using a moving window approach? I initially tried using Fragstats, but there seems to be a glitch in the program when running on Windows 10, and it is my understanding that is no longer being updated/debugged.  I appreciate any information you can provide. Thanks!

**Comment by bitbacchus** [comment] 2021-03-24 08:53
You can estimate the expected run time by benchmarking (e.g. `mircobenchmark`) the run time of lsm_l_p on a 161x161 matrix of your landscape and multiplying this measure by the number of cells in your landscape. 

For example, `lsm_l_p` has an average run time of 0.008 s for a 30 x 30 landscape (`landscapemetrics::landscape`)
 and 0.18 s for a 400 x 679 landscape (`landscapemetrics::augusta_nlcd`). Based on this, the estimated calculation time using a moving window of size 30x30 in a landscape with 5.6 million cells would be about 12.5 hrs. Same with a moving window of size 400 x 679 would take 11-12 days. As this scales better than linear, I'd expect a run time of something like a week for your calculation on my machine.

We are currently exploring ideas on how to improve performance for this (#224), but for now, you'll have to be patient...

**Comment by mhesselbarth** [comment] 2021-03-24 11:40
@bitbacchus That's a smart idea. I haven't thought about this yet! 
@JKLockhart Your code looks correct and as already mentioned `window_lsm` is not the fastest function.

Will close issue for now.

**Closed by mhesselbarth** 2021-03-24 11:40 UTC
Labels: enhancement, question
